// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.6
// source: define.proto

// 指定proto版本

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 合约交易状态类型
type InstStatus int32

const (
	InstStatus_IST_UNKNOWN                InstStatus = 0  // 默认值 (byte值: 0x00, 0)
	InstStatus_IST_BEFORE_TRADING         InstStatus = 48 // 开盘前 (byte值: 0x30, '0')
	InstStatus_IST_NO_TRADING             InstStatus = 49 // 非交易 (byte值: 0x31, '1')
	InstStatus_IST_CONTINUE               InstStatus = 50 // 连续交易 (byte值: 0x32, '2')
	InstStatus_IST_AUCTION_ORDERING       InstStatus = 51 // 集合竞价报单 (byte值: 0x33, '3')
	InstStatus_IST_AUCTION_BALANCE        InstStatus = 52 // 集合竞价价格平衡 (byte值: 0x34, '4')
	InstStatus_IST_AUCTION_MATCH          InstStatus = 53 // 集合竞价撮合 (byte值: 0x35, '5')
	InstStatus_IST_CLOSE                  InstStatus = 54 // 收盘 (byte值: 0x36, '6')
	InstStatus_IST_TRANSACTION_PROCESSING InstStatus = 55 // 交易业务处理 (byte值: 0x37, '7')
)

// Enum value maps for InstStatus.
var (
	InstStatus_name = map[int32]string{
		0:  "IST_UNKNOWN",
		48: "IST_BEFORE_TRADING",
		49: "IST_NO_TRADING",
		50: "IST_CONTINUE",
		51: "IST_AUCTION_ORDERING",
		52: "IST_AUCTION_BALANCE",
		53: "IST_AUCTION_MATCH",
		54: "IST_CLOSE",
		55: "IST_TRANSACTION_PROCESSING",
	}
	InstStatus_value = map[string]int32{
		"IST_UNKNOWN":                0,
		"IST_BEFORE_TRADING":         48,
		"IST_NO_TRADING":             49,
		"IST_CONTINUE":               50,
		"IST_AUCTION_ORDERING":       51,
		"IST_AUCTION_BALANCE":        52,
		"IST_AUCTION_MATCH":          53,
		"IST_CLOSE":                  54,
		"IST_TRANSACTION_PROCESSING": 55,
	}
)

func (x InstStatus) Enum() *InstStatus {
	p := new(InstStatus)
	*p = x
	return p
}

func (x InstStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_define_proto_enumTypes[0].Descriptor()
}

func (InstStatus) Type() protoreflect.EnumType {
	return &file_define_proto_enumTypes[0]
}

func (x InstStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstStatus.Descriptor instead.
func (InstStatus) EnumDescriptor() ([]byte, []int) {
	return file_define_proto_rawDescGZIP(), []int{0}
}

var file_define_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "pb.cn_name",
		Tag:           "bytes,50000,opt,name=cn_name",
		Filename:      "define.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string cn_name = 50000;
	E_CnName = &file_define_proto_extTypes[0]
)

var File_define_proto protoreflect.FileDescriptor

const file_define_proto_rawDesc = "" +
	"\n" +
	"\fdefine.proto\x12\x02pb\x1a google/protobuf/descriptor.proto*\x88\x03\n" +
	"\n" +
	"InstStatus\x12!\n" +
	"\vIST_UNKNOWN\x10\x00\x1a\x10\x82\xb5\x18\f未知状态\x12%\n" +
	"\x12IST_BEFORE_TRADING\x100\x1a\r\x82\xb5\x18\t开盘前\x12!\n" +
	"\x0eIST_NO_TRADING\x101\x1a\r\x82\xb5\x18\t非交易\x12\"\n" +
	"\fIST_CONTINUE\x102\x1a\x10\x82\xb5\x18\f连续交易\x120\n" +
	"\x14IST_AUCTION_ORDERING\x103\x1a\x16\x82\xb5\x18\x12集合竞价报单\x125\n" +
	"\x13IST_AUCTION_BALANCE\x104\x1a\x1c\x82\xb5\x18\x18集合竞价价格平衡\x12-\n" +
	"\x11IST_AUCTION_MATCH\x105\x1a\x16\x82\xb5\x18\x12集合竞价撮合\x12\x19\n" +
	"\tIST_CLOSE\x106\x1a\n" +
	"\x82\xb5\x18\x06收盘\x126\n" +
	"\x1aIST_TRANSACTION_PROCESSING\x107\x1a\x16\x82\xb5\x18\x12交易业务处理:<\n" +
	"\acn_name\x12!.google.protobuf.EnumValueOptions\x18І\x03 \x01(\tR\x06cnNameB/Z-github.com/crazy-choose/helper/model/proto/pbb\x06proto3"

var (
	file_define_proto_rawDescOnce sync.Once
	file_define_proto_rawDescData []byte
)

func file_define_proto_rawDescGZIP() []byte {
	file_define_proto_rawDescOnce.Do(func() {
		file_define_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_define_proto_rawDesc), len(file_define_proto_rawDesc)))
	})
	return file_define_proto_rawDescData
}

var file_define_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_define_proto_goTypes = []any{
	(InstStatus)(0),                       // 0: pb.InstStatus
	(*descriptorpb.EnumValueOptions)(nil), // 1: google.protobuf.EnumValueOptions
}
var file_define_proto_depIdxs = []int32{
	1, // 0: pb.cn_name:extendee -> google.protobuf.EnumValueOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_define_proto_init() }
func file_define_proto_init() {
	if File_define_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_define_proto_rawDesc), len(file_define_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_define_proto_goTypes,
		DependencyIndexes: file_define_proto_depIdxs,
		EnumInfos:         file_define_proto_enumTypes,
		ExtensionInfos:    file_define_proto_extTypes,
	}.Build()
	File_define_proto = out.File
	file_define_proto_goTypes = nil
	file_define_proto_depIdxs = nil
}
